# --- !Ups

create table "PRODUCTS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"ean" BIGINT NOT NULL,"name" VARCHAR NOT NULL,"description" VARCHAR NOT NULL);

insert into PRODUCTS values (1, 1234567, 'shoes','a pair of shoes');
insert into PRODUCTS values (2, 789101112, 'clothing', 'some clothes');
insert into PRODUCTS values (3, 1314151617, 'bags', 'a nice bag');

# --- !Downs

drop table "PRODUCTS";

